### PR TITLE
[WIP] Support danish

### PR DESCRIPTION
**Pull request by mollerhoj**
Hey man, thanks for a great project.

I think I'd be nice to have a Danish version of the segmenter.

I've copied most of the rules from the German (Deutsch?) segmenter, as they seem quite good.

I copied the English spec, and translated on the specs that failed (I'm lazy).

Some specs fail regardless, and I don't understand why. Some the the codebase seems a little convoluted - Could you help me out?

### CODE REVIEW

**Comment by diasks2** [comment]
Thanks for working on that! It would be great to improve/support Danish. Unfortunately, I won't have any time to help out with taking a look at this in the near future, but if anyone else watching this thread can that would be much appreciated.

**Comment by mollerhoj** [comment]
@diasks2 I could just remove/skip the failing specs, but I'd rather give you an opportunity to have a look. I might get the time to have a look at what's causing them to fail.

**Comment by diasks2** [comment]
Yeah, if they are failing I'd like to understand why so we can fix it. Maybe I can take a look this weekend.

**Comment by mollerhoj** [comment]
@diasks2 I had another look at this. Turns out I'd made a few mistakes. I've updated the code, and all specs except for the dreaded #018 rule now passes

**Comment by diasks2** [comment]
Thanks! Sorry for the delayed response, was out of town.

**Pull request merged**
